name: Build Windows executable
on: workflow_dispatch
#  release:
#    types: [published]

env:
  CARGO_TERM_COLOR: always
  temp_path: 'C:\action_temp'
  vcbt_uri: 'https://aka.ms/vs/16/release/vs_buildtools.exe'
  vcbt_installer: 'C:\buildtools_installer.exe'
  vsynth_uri: 'https://github.com/vapoursynth/vapoursynth/releases/download/R58/VapourSynth64-Portable-R58.7z'
  vsynth_path: 'C:\vapoursynth'
  nasm_uri: 'https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip'

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Setup FFmpeg 5.0
      uses: Iamshankhadeep/setup-ffmpeg@v1.1
      with:
        version: "5.0"
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '~3.10'
        architecture: 'x64'

#     - name: Check cache for NASM
#       id: cache-nasm
#       uses: actions/cache@v3
#       with:
#         path: ${{ env.nasm_path }}
#         key: ${{ hashFiles('$env:nasm_path\nasm.exe') }}
    #- if: ${{ steps.cache-nasm.outputs.cache-hit == 'false' }}
    - name: Install NASM
      run: |
        $tempFile = New-TemporaryFile
        Invoke-WebRequest -Uri $env:nasm_uri -OutFile $tempFile -TimeoutSec 10
        Expand-Archive -LiteralPath $tempFile -DestinationPath 'C:\'
        (Get-Item 'C:\nasm*').FullPath | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - run: |
        echo $env:PATH
        nasm --version

    - name: Install VapourSynth
      run: |
        Install-Module -Name 7Zip4Powershell -Force
        $tempFile = New-TemporaryFile
        Invoke-WebRequest -Uri $env:vsynth_uri -OutFile $tempFile -TimeoutSec 10
        Expand-7Zip -ArchiveFileName $tempFile -TargetPath $env:vsynth_path
        echo vsynth_path | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - run: echo $env:PATH
    
    - name: Install Visual C++ Build Tools
      run: |
        (start /w vs_buildtools.exe --quiet --wait --norestart --nocache `
          --installPath "$env:ProgramFiles(x86)\Microsoft Visual Studio\2022\BuildTools" `
          --add Microsoft.VisualStudio.Workload.AzureBuildTools `
          --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
          --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
          --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
          --remove Microsoft.VisualStudio.Component.Windows81SDK `
          || IF "%ERRORLEVEL%"=="3010" EXIT 0) `

#     - name: Cache deps
#       id: cache
#       uses: actions/cache@v3
#       with:
#         path: 

#     - name: Download Dependencies
#       run: |
#         
#         Invoke-WebRequest -Uri $env:vcbt_uri -OutFile $env:vcbt_installer -TimeoutSec 10
#     - name: Install Dependencies
#       run: |
#         '& $env:vcbt_installer'
#         '& $env:vsynth_zip /ALLUSERS'
#     - uses: actions/checkout@v3
#     - name: Build Av1an
#       run: cargo build -r --verbose
