name: Build Windows executable
on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - uses: Iamshankhadeep/setup-ffmpeg@v1.1
      with:
        version: "4.4"
    - name: Build
      run: cargo build -r --verbose
