name: Build Windows executable
on: workflow_dispatch
#  release:
#    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-2022

    steps:
    - run: mkdir Download
    - name: Download Visual C++ Build Tools
      run: Invoke-WebRequest -Uri 'https://aka.ms/vs/16/release/vs_buildtools.exe' -ContentType application -TransferEncoding gzip -TimeoutSec 10
      working-directory: Download
    - run: ls
      working-directory: Download
    - name: Install Visual C++ Build Tools
      run: vs_buildtools.exe
      working-directory: Download
      
      
    #- uses: actions/checkout@v3
    #- uses: Iamshankhadeep/setup-ffmpeg@v1.1
    #  with:
    #    version: "4.4"
    #- uses: actions/setup-python@v4
    #  with:
    #    python-version: '~3.10'
    #    architecture: 'x64'
    #- name: Build
    #  run: cargo build -r --verbose
