name: Build Windows executable
on: workflow_dispatch
#  release:
#    types: [published]

env:
  CARGO_TERM_COLOR: always
  vcbt_uri: 'https://aka.ms/vs/16/release/vs_buildtools.exe'
  vcbt_installer: 'C:\buildtools_installer.exe'
  vsynth_uri: 'https://github.com/vapoursynth/vapoursynth/releases/download/R58/VapourSynth64-R58.exe'
  vsynth_installer: 'C:\vapoursynth_installer.exe'
  nasm_uri: 'https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip'
  nasm_zip: 'C:\nasm.zip'
  nasm_path: 'C:\NASM'

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Setup FFmpeg 5.0
      uses: Iamshankhadeep/setup-ffmpeg@v1.1
      with:
        version: "5.0"
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '~3.10'
        architecture: 'x64'

#     - name: Check cache for NASM
#       uses: actions/cache@v3
#       with:
#         path: ${{ env.nasm_path }}
#         key: ${{ hashFiles('$env:nasm_path\nasm.exe') }}
    - name: Install NASM
      run: |
        Invoke-WebRequest -Uri $env:nasm_uri -OutFile $env:nasm_zip -TimeoutSec 10
        Expand-Archive -LiteralPath $env:nasm_zip -DestinationPath $env:nasm_path
        echo $env:nasm_path | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        ls $env:nasm_path

#     - name: Cache deps
#       id: cache
#       uses: actions/cache@v3
#       with:
#         path: 

#     - name: Download Dependencies
#       run: |
#         
#         Invoke-WebRequest -Uri $env:vcbt_uri -OutFile $env:vcbt_installer -TimeoutSec 10
#         Invoke-WebRequest -Uri $env:vsynth_uri -OutFile $env:vsynth_installer -TimeoutSec 10
#     - name: Install Dependencies
#       run: |
#         '& $env:vcbt_installer'
#         '& $env:vsynth_installer /ALLUSERS'
#     - uses: actions/checkout@v3
#     - name: Build Av1an
#       run: cargo build -r --verbose
