name: Build Windows executable
on: workflow_dispatch
#  release:
#    types: [published]

env:
  CARGO_TERM_COLOR: always
  temp_path: 'C:\action_temp'
  vcbt_uri: 'https://aka.ms/vs/16/release/vs_buildtools.exe'
  vcbt_installer: 'C:\buildtools_installer.exe'
  vsynth_uri: 'https://github.com/vapoursynth/vapoursynth/releases/download/R58/VapourSynth64-Portable-R58.7z'
  vsynth_path: 'C:\vapoursynth'

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Setup FFmpeg 5.0\
      id: setup-ffmpeg
      uses: Iamshankhadeep/setup-ffmpeg@v1.1
      with:
        version: "5.0"
    - run: echo "FFMPEG_DIR=${{ steps.setup-ffmpeg.outputs.ffmpeg-path }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '~3.10'
        architecture: 'x64'

    - name: Setup NASM
      uses: ilammy/setup-nasm@v1
      with:
        version: 2.15.05
        from-source: false

    - name: Install VapourSynth
      run: |
        Install-Module -Name 7Zip4Powershell -Force
        $tempFile = New-TemporaryFile
        Invoke-WebRequest -Uri $env:vsynth_uri -OutFile $tempFile -TimeoutSec 10
        Expand-7Zip -ArchiveFileName $tempFile -TargetPath $env:vsynth_path
        echo $env:vsynth_path | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Install Visual C++ Build Tools
      run: |
        Invoke-WebRequest -Uri $env:vcbt_uri -OutFile $env:vcbt_installer -TimeoutSec 10
        '& $env:vcbt_installer --quiet --wait --norestart --nocache --installPath C:\BuildTools --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.ASAN --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64'

    - uses: actions/checkout@v3
    - name: Build Av1an
      run: cargo build -r --verbose
    - run: ls target
