name: Build Windows executable
on: workflow_dispatch
#  release:
#    types: [published]

env:
  CARGO_TERM_COLOR: always
  VSBT_URI: 'https://aka.ms/vs/16/release/vs_buildtools.exe'
  VSBT_INSTALLER: 'C:\buildtools_installer.exe'
  VAPOURSYNTH_URI: 'https://github.com/vapoursynth/vapoursynth/releases/download/R58/VapourSynth64-R58.exe'
  VAPOURSYNTH_INSTALLER: 'C:/vapoursynth_installer.exe'

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Download Vapoursynth
      run: Invoke-WebRequest -Uri $env:VAPOURSYNTH_URI -OutFile $env:VAPOURSYNTH_INSTALLER -TimeoutSec 10
    - name: Install Vapoursynth
      run: '& $env:VAPOURSYNTH_INSTALLER'
    #- name: Download Visual C++ Build Tools
    #  run: Invoke-WebRequest -Uri $env:VSBT_URI -OutFile $env:VSBT_INSTALLER -TimeoutSec 10
    #- name: Install Visual C++ Build Tools
    #  run: '& $env:VSBT_INSTALLER'
    #- uses: actions/checkout@v3
    #- uses: Iamshankhadeep/setup-ffmpeg@v1.1
    #  with:
    #    version: "4.4"
    #- uses: actions/setup-python@v4
    #  with:
    #    python-version: '~3.10'
    #    architecture: 'x64'
    #- name: Build
    #  run: cargo build -r --verbose
